{% set name = "fonduer" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdbedcdb78143e7e9867d38c14fc65357c01b886786763f2b163eb8773bbfce4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - beautifulsoup4 ==4.7.1
    - editdistance >=0.5.2
    - emmental >=0.0.6
    - ipython
    - lxml >=4.2.5
    - numpy >=1.11
    - pyyaml >=5.1
    - scipy >=1.1.0
    - snorkel >=0.9.5
    - spacy >=2.1.3
    - sqlalchemy >=1.3.7
    - postgresql
    - pytorch >=1.3.1,<2.0.0
    - tqdm >=4.36.0
    - treedlib >=0.1.1
    - wand >=0.4.4
    - tensorboardx
    - deprecation

test:
  imports:
    - fonduer
    - fonduer.candidates
    - fonduer.candidates.models
    - fonduer.features
    - fonduer.features.feature_libs
    - fonduer.features.models
    - fonduer.learning
    - fonduer.learning.models
    - fonduer.learning.modules
    - fonduer.parser
    - fonduer.parser.lingual_parser
    - fonduer.parser.models
    - fonduer.parser.preprocessors
    - fonduer.supervision
    - fonduer.supervision.models
    - fonduer.utils
    - fonduer.utils.data_model_utils
    - fonduer.utils.logging
    - fonduer.utils.models

about:
  home: https://github.com/HazyResearch/fonduer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fonduer is a Python package and framework for building knowledge base construction (KBC) applications from richly formatted data.
  doc_url: https://fonduer.readthedocs.io/
  dev_url: https://github.com/HazyResearch/fonduer

extra:
  recipe-maintainers:
    - npavlovikj
